//------------------------------------------------------------------------------
// <auto-generated>
//     Designer code для Form1: перемещён и увеличен statsGroupBox,
//     чтобы отображать все 10 строк топа слов и символов.
//------------------------------------------------------------------------------

namespace WordCountProgram
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.inputTextBox = new System.Windows.Forms.TextBox();
            this.analyzeButton = new System.Windows.Forms.Button();
            this.loadFileButton = new System.Windows.Forms.Button();
            this.clearButton = new System.Windows.Forms.Button();
            this.filterLabel = new System.Windows.Forms.Label();
            this.filterlabel1 = new System.Windows.Forms.Label();
            this.filterTextBox = new System.Windows.Forms.TextBox();
            this.statsGroupBox = new System.Windows.Forms.GroupBox();
            this.textSizeLabel = new System.Windows.Forms.Label();
            this.avgSentenceLengthLabel = new System.Windows.Forms.Label();
            this.avgWordLengthLabel = new System.Windows.Forms.Label();
            this.sentencesLabel = new System.Windows.Forms.Label();
            this.spacesLabel = new System.Windows.Forms.Label();
            this.topCharsLabel = new System.Windows.Forms.Label();
            this.topWordsLabel = new System.Windows.Forms.Label();
            this.totalWordsLabel = new System.Windows.Forms.Label();
            this.statsGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // inputTextBox
            // 
            this.inputTextBox.Dock = System.Windows.Forms.DockStyle.Top;
            this.inputTextBox.Location = new System.Drawing.Point(0, 0);
            this.inputTextBox.Multiline = true;
            this.inputTextBox.Name = "inputTextBox";
            this.inputTextBox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.inputTextBox.Size = new System.Drawing.Size(784, 160);
            this.inputTextBox.TabIndex = 0;
            // 
            // analyzeButton
            // 
            this.analyzeButton.Location = new System.Drawing.Point(12, 170);
            this.analyzeButton.Name = "analyzeButton";
            this.analyzeButton.Size = new System.Drawing.Size(120, 32);
            this.analyzeButton.TabIndex = 1;
            this.analyzeButton.Text = "Анализировать";
            this.analyzeButton.UseVisualStyleBackColor = true;
            this.analyzeButton.Click += new System.EventHandler(this.analyzeButton_Click);
            // 
            // loadFileButton
            // 
            this.loadFileButton.Location = new System.Drawing.Point(138, 170);
            this.loadFileButton.Name = "loadFileButton";
            this.loadFileButton.Size = new System.Drawing.Size(120, 32);
            this.loadFileButton.TabIndex = 2;
            this.loadFileButton.Text = "Загрузить файл";
            this.loadFileButton.UseVisualStyleBackColor = true;
            this.loadFileButton.Click += new System.EventHandler(this.loadFileButton_Click);
            // 
            // clearButton
            // 
            this.clearButton.Location = new System.Drawing.Point(264, 170);
            this.clearButton.Name = "clearButton";
            this.clearButton.Size = new System.Drawing.Size(120, 32);
            this.clearButton.TabIndex = 3;
            this.clearButton.Text = "Очистить";
            this.clearButton.UseVisualStyleBackColor = true;
            this.clearButton.Click += new System.EventHandler(this.clearButton_Click);
            // 
            // filterLabel
            // 
            this.filterLabel.AutoSize = true;
            this.filterLabel.Location = new System.Drawing.Point(390, 220);
            this.filterLabel.Name = "filterLabel";
            this.filterLabel.Size = new System.Drawing.Size(100, 13);
            this.filterLabel.TabIndex = 4;
            this.filterLabel.Text = "Мин. длина слова:";
            // 
            // filterlabel1
            // 
            this.filterlabel1.AutoSize = true;
            this.filterlabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.filterlabel1.Location = new System.Drawing.Point(390, 236);
            this.filterlabel1.Name = "filterlabel1";
            this.filterlabel1.Size = new System.Drawing.Size(41, 13);
            this.filterlabel1.TabIndex = 5;
            this.filterlabel1.Text = "(число)";
            // 
            // filterTextBox
            // 
            this.filterTextBox.Location = new System.Drawing.Point(440, 233);
            this.filterTextBox.Name = "filterTextBox";
            this.filterTextBox.Size = new System.Drawing.Size(80, 20);
            this.filterTextBox.TabIndex = 6;
            // 
            // statsGroupBox
            // 
            this.statsGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.statsGroupBox.Controls.Add(this.textSizeLabel);
            this.statsGroupBox.Controls.Add(this.avgSentenceLengthLabel);
            this.statsGroupBox.Controls.Add(this.avgWordLengthLabel);
            this.statsGroupBox.Controls.Add(this.sentencesLabel);
            this.statsGroupBox.Controls.Add(this.spacesLabel);
            this.statsGroupBox.Controls.Add(this.topCharsLabel);
            this.statsGroupBox.Controls.Add(this.topWordsLabel);
            this.statsGroupBox.Controls.Add(this.totalWordsLabel);
            this.statsGroupBox.Location = new System.Drawing.Point(12, 260);
            this.statsGroupBox.Name = "statsGroupBox";
            this.statsGroupBox.Size = new System.Drawing.Size(760, 360);
            this.statsGroupBox.TabIndex = 7;
            this.statsGroupBox.TabStop = false;
            this.statsGroupBox.Text = "Статистика";
            // 
            // textSizeLabel
            // 
            this.textSizeLabel.AutoSize = true;
            this.textSizeLabel.Location = new System.Drawing.Point(400, 225);
            this.textSizeLabel.Name = "textSizeLabel";
            this.textSizeLabel.Size = new System.Drawing.Size(121, 13);
            this.textSizeLabel.TabIndex = 7;
            this.textSizeLabel.Text = "Размер текста: 0 байт";
            // 
            // avgSentenceLengthLabel
            // 
            this.avgSentenceLengthLabel.AutoSize = true;
            this.avgSentenceLengthLabel.Location = new System.Drawing.Point(400, 175);
            this.avgSentenceLengthLabel.Name = "avgSentenceLengthLabel";
            this.avgSentenceLengthLabel.Size = new System.Drawing.Size(166, 13);
            this.avgSentenceLengthLabel.TabIndex = 6;
            this.avgSentenceLengthLabel.Text = "Средняя длина предложения: 0";
            // 
            // avgWordLengthLabel
            // 
            this.avgWordLengthLabel.AutoSize = true;
            this.avgWordLengthLabel.Location = new System.Drawing.Point(400, 150);
            this.avgWordLengthLabel.Name = "avgWordLengthLabel";
            this.avgWordLengthLabel.Size = new System.Drawing.Size(128, 13);
            this.avgWordLengthLabel.TabIndex = 5;
            this.avgWordLengthLabel.Text = "Средняя длина слова: 0";
            // 
            // sentencesLabel
            // 
            this.sentencesLabel.AutoSize = true;
            this.sentencesLabel.Location = new System.Drawing.Point(400, 125);
            this.sentencesLabel.Name = "sentencesLabel";
            this.sentencesLabel.Size = new System.Drawing.Size(89, 13);
            this.sentencesLabel.TabIndex = 4;
            this.sentencesLabel.Text = "Предложений: 0";
            // 
            // spacesLabel
            // 
            this.spacesLabel.AutoSize = true;
            this.spacesLabel.Location = new System.Drawing.Point(400, 100);
            this.spacesLabel.Name = "spacesLabel";
            this.spacesLabel.Size = new System.Drawing.Size(69, 13);
            this.spacesLabel.TabIndex = 3;
            this.spacesLabel.Text = "Пробелов: 0";
            // 
            // topCharsLabel
            // 
            this.topCharsLabel.Location = new System.Drawing.Point(6, 200);
            this.topCharsLabel.Name = "topCharsLabel";
            this.topCharsLabel.Size = new System.Drawing.Size(350, 150);
            this.topCharsLabel.TabIndex = 2;
            this.topCharsLabel.Text = "Топ-10 символов:";
            // 
            // topWordsLabel
            // 
            this.topWordsLabel.Location = new System.Drawing.Point(6, 25);
            this.topWordsLabel.Name = "topWordsLabel";
            this.topWordsLabel.Size = new System.Drawing.Size(350, 170);
            this.topWordsLabel.TabIndex = 1;
            this.topWordsLabel.Text = "Топ-10 слов:";
            // 
            // totalWordsLabel
            // 
            this.totalWordsLabel.AutoSize = true;
            this.totalWordsLabel.Location = new System.Drawing.Point(400, 25);
            this.totalWordsLabel.Name = "totalWordsLabel";
            this.totalWordsLabel.Size = new System.Drawing.Size(142, 13);
            this.totalWordsLabel.TabIndex = 0;
            this.totalWordsLabel.Text = "Общее количество слов: 0";
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 661);
            this.Controls.Add(this.statsGroupBox);
            this.Controls.Add(this.filterTextBox);
            this.Controls.Add(this.filterlabel1);
            this.Controls.Add(this.filterLabel);
            this.Controls.Add(this.clearButton);
            this.Controls.Add(this.loadFileButton);
            this.Controls.Add(this.analyzeButton);
            this.Controls.Add(this.inputTextBox);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(800, 700);
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Анализатор Текста";
            this.statsGroupBox.ResumeLayout(false);
            this.statsGroupBox.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TextBox inputTextBox;
        private System.Windows.Forms.Button analyzeButton;
        private System.Windows.Forms.Button loadFileButton;
        private System.Windows.Forms.Button clearButton;
        private System.Windows.Forms.Label filterLabel;
        private System.Windows.Forms.Label filterlabel1;
        private System.Windows.Forms.TextBox filterTextBox;
        private System.Windows.Forms.GroupBox statsGroupBox;
        private System.Windows.Forms.Label totalWordsLabel;
        private System.Windows.Forms.Label topWordsLabel;
        private System.Windows.Forms.Label topCharsLabel;
        private System.Windows.Forms.Label spacesLabel;
        private System.Windows.Forms.Label sentencesLabel;
        private System.Windows.Forms.Label avgWordLengthLabel;
        private System.Windows.Forms.Label avgSentenceLengthLabel;
        private System.Windows.Forms.Label textSizeLabel;
    }
}
